### PR TITLE
Introduction to Zoplicate

### PR DESCRIPTION
**Pull request by ChenglongMa**
Please check https://github.com/ChenglongMa/zoplicate for more details.

@algora-pbc /claim #14

### CODE REVIEW

**Comment by quinn-p-mchugh** [comment]
@ChenglongMa
Hi ChenglongMa, I tried to send you $50 through Algora, but there seems to be a bug that ends up queueing the wrong amount to Stripe.

Do you have PayPal by chance? If you provide me an email, I can send it that way instead.

Apologies for the confusion. This is my first time using Algora.

**Comment by ChenglongMa** [comment]
Hi @quinn-p-mchugh,

Thanks for your support. My PayPal email is chenglong.m@outlook.com.

It is my first time using Algora and PayPal as well 😂.

Please let me know if I need to do anything else.

**Comment by quinn-p-mchugh** [comment]
Sent - thanks again!

image

**Comment by ChenglongMa** [comment]
Wow @quinn-p-mchugh, thank you for your sponsorship! I am very appreciative of it.

**Pull request closed without merging**
